server {
        listen  4444;

        root    /srv/http/sqltest/sqlite;
        index   index.html;

        location / {
                try_files $uri $uri/ = 404;
        }
        location /login {
            proxy_pass          http://sqlite:8484/login;
            proxy_http_version  1.1;
            proxy_set_header    Host $host;
        }
}
