#!/usr/bin/env ruby

require 'optparse'
require 'uri'
require 'net/http'

class SpiderConfig
  attr_accessor :url, :path, :level, :recursive

  def initialize(url, path = "./data/", level = 1, recursive = false)
    @url = url
    @path = path
    @level = level
    @recursive = recursive 
  end 
end

def usage()
  puts "./spider [-r recursive] [-l recursive_level] [-p path] {URL}" 
  exit
end

def parse_input(input, config)
  if input.length <= 0 || input.length >= 6
    usage()
  end

  OptionParser.new do |opts|
  opts.on("-r", "--recursive", "Enable recursivity") do
    config.recursive = true
  end
  opts.on("-lLEVEL", "--level=LEVEL", Integer, "Max recursivity level") do |level|
    config.level = level
  end
  opts.on("-pPATH", "--path=PATH", "Output Directory") do |path|
    config.path = path
  end
  end.parse!

end

def make_request(url)
  uri = URI(url)

  res = Net::HTTP.get_response(uri)
  if res.is_a?(Net::HTTPSuccess)
    return res.body 
  else
    puts "response failed"
    return nil
  end
end

def extract_images(url, content)
  images = []
  content.scan(/<img[^>]+src=["']([^"']+)["']/i) do |match|
  extension = File.extname(match[0])
  if not (extension == ".png" || extension == ".jpg" || extension == ".jpeg" || extension == ".gif" || extension == ".bmp")  
    return 
  end
  base = url.match(%r{(https?://[^/]+)})[1]
  full_url = base + match[0]
  images << full_url 
  end
  return images
end

def save_images(path, images)
  if images.empty?
    return
  end
  images.each_with_index do | image, i |
    filename = File.join(path, "image_#{i}" + File.extname(image))
    begin
      File.open(filename, "w") do |file|
        res = Net::HTTP.get_response(URI(image))
        file.write(res.body)
      end
    rescue Errno::ENOENT
      puts "[SPIDER] not found: #{path}"
      exit
    rescue Errno::EACCES
      puts "[SPIDER] Permission denied on : #{path}"
    end 
    puts filename
  end
end

def spider(url, path, level)
  if (level == 0)
    return 
  end
  content = make_request(url)
  if content.nil?
    return spider(url, path, level - 1) 
  end
  puts content
  #save_page(content)
  images = extract_images(url, content)
  save_images(path, images)
  spider(url, path, level - 1)
end

def main
  input = ARGV
  url = ARGV[-1]
  conf = SpiderConfig.new(url)
  parse_input(input, conf) 
  if (conf.recursive)
    spider(conf.url, conf.path, conf.level)
  else
    spider(conf.url, conf.path, 1)
  end
end

main

# conseguir la pagina
# guardar la pagina 
# extraer todas las imagenes de la pagina
# Guardar en el path indicado las imagenes.
