FROM alpine:3.18

RUN apk update && apk add --no-cache \
    linux-headers \
    libpcap-dev \
    iproute2 \
    tcpdump \
	lftp

COPY ./file1.txt /home/ 
COPY ./file2.txt /home/ 
COPY ./file3.txt /home/ 

CMD ["tail", "-f", "/dev/null"]
